/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./character_final.glb');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig">
          <group
            name="spine"
            position={[0, 0.32, -0.02]}
            rotation={[0.25, 0, 0]}>
            <group name="pelvisL" rotation={[-2.03, -0.82, -2.24]} />
            <group name="pelvisR" rotation={[-2.03, 0.82, 2.24]} />
            <group
              name="spine001"
              position={[0, 0.06, 0]}
              rotation={[-0.13, 0, 0]}>
              <group
                name="spine002"
                position={[0, 0.05, 0]}
                rotation={[-0.16, 0, 0]}>
                <group name="spine003" position={[0, 0.07, 0]}>
                  <group
                    name="breastL"
                    position={[0.05, -0.02, -0.02]}
                    rotation={[-1.54, 0, Math.PI]}
                  />
                  <group
                    name="breastR"
                    position={[-0.05, -0.02, -0.02]}
                    rotation={[-1.54, 0, -Math.PI]}
                  />
                  <group
                    name="shoulderL"
                    position={[0.01, 0.05, 0.03]}
                    rotation={[-1.54, 0, -1.04]}>
                    <group
                      name="upper_armL"
                      position={[0.02, 0.1, -0.03]}
                      rotation={[1.91, 1.14, -2.33]}>
                      <group
                        name="forearmL"
                        position={[0, 0.1, 0]}
                        rotation={[0.28, -0.15, -0.12]}>
                        <group
                          name="handL"
                          position={[0, 0.14, 0]}
                          rotation={[-2.55, 1.42, 2.43]}>
                          <group
                            name="palm01L"
                            position={[-0.03, 0.05, 0]}
                            rotation={[0.09, -0.09, 0.18]}>
                            <group
                              name="f_index01L"
                              position={[0, 0.03, 0]}
                              rotation={[0.31, 0.07, -0.18]}>
                              <group
                                name="f_index02L"
                                position={[0, 0.02, 0]}
                                rotation={[-0.01, 0.07, 0.05]}
                              />
                            </group>
                            <group
                              name="thumb01L"
                              position={[-0.01, -0.02, 0.03]}
                              rotation={[-1.29, 1.25, 1.53]}>
                              <group
                                name="thumb02L"
                                position={[0, 0.04, 0]}
                                rotation={[0.11, 0.08, -0.01]}
                              />
                            </group>
                          </group>
                          <group
                            name="palm02L"
                            position={[-0.01, 0.05, -0.01]}
                            rotation={[0.19, -0.12, -0.04]}>
                            <group
                              name="f_middle01L"
                              position={[0, 0.04, 0]}
                              rotation={[0.2, 0.15, 0.01]}>
                              <group
                                name="f_middle02L"
                                position={[0, 0.02, 0]}
                                rotation={[0, -0.01, 0.01]}
                              />
                            </group>
                          </group>
                          <group
                            name="palm03L"
                            position={[0.01, 0.05, 0]}
                            rotation={[0.13, -0.15, -0.05]}>
                            <group
                              name="f_ring01L"
                              position={[0, 0.04, 0]}
                              rotation={[0.39, 0.07, -0.02]}>
                              <group
                                name="f_ring02L"
                                position={[0, 0.02, 0]}
                                rotation={[-0.14, 0.02, 0]}
                              />
                            </group>
                          </group>
                          <group
                            name="palm04L"
                            position={[0.03, 0.05, 0]}
                            rotation={[0.17, -0.12, -0.28]}>
                            <group
                              name="f_pinky01L"
                              position={[0, 0.04, 0]}
                              rotation={[0.2, 0.04, 0.19]}>
                              <group
                                name="f_pinky02L"
                                position={[0, 0.01, 0]}
                                rotation={[0.04, -0.02, 0.06]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="shoulderR"
                    position={[-0.01, 0.05, 0.03]}
                    rotation={[-1.54, 0, 1.04]}>
                    <group
                      name="upper_armR"
                      position={[-0.02, 0.1, -0.03]}
                      rotation={[1.91, -1.14, 2.33]}>
                      <group
                        name="forearmR"
                        position={[0, 0.1, 0]}
                        rotation={[0.28, 0.15, 0.12]}>
                        <group
                          name="handR"
                          position={[0, 0.14, 0]}
                          rotation={[-2.55, -1.42, -2.43]}>
                          <group
                            name="palm01R"
                            position={[0.03, 0.05, 0]}
                            rotation={[0.09, 0.09, -0.18]}>
                            <group
                              name="f_index01R"
                              position={[0, 0.03, 0]}
                              rotation={[0.31, -0.07, 0.18]}>
                              <group
                                name="f_index02R"
                                position={[0, 0.02, 0]}
                                rotation={[-0.01, -0.07, -0.05]}
                              />
                            </group>
                            <group
                              name="thumb01R"
                              position={[0.01, -0.02, 0.03]}
                              rotation={[-1.29, -1.25, -1.53]}>
                              <group
                                name="thumb02R"
                                position={[0, 0.04, 0]}
                                rotation={[0.11, -0.08, 0.01]}
                              />
                            </group>
                          </group>
                          <group
                            name="palm02R"
                            position={[0.01, 0.05, -0.01]}
                            rotation={[0.19, 0.12, 0.04]}>
                            <group
                              name="f_middle01R"
                              position={[0, 0.04, 0]}
                              rotation={[0.2, -0.15, -0.01]}>
                              <group
                                name="f_middle02R"
                                position={[0, 0.02, 0]}
                                rotation={[0, 0.01, -0.01]}
                              />
                            </group>
                          </group>
                          <group
                            name="palm03R"
                            position={[-0.01, 0.05, 0]}
                            rotation={[0.13, 0.15, 0.05]}>
                            <group
                              name="f_ring01R"
                              position={[0, 0.04, 0]}
                              rotation={[0.39, -0.07, 0.02]}>
                              <group
                                name="f_ring02R"
                                position={[0, 0.02, 0]}
                                rotation={[-0.14, -0.02, 0]}
                              />
                            </group>
                          </group>
                          <group
                            name="palm04R"
                            position={[-0.03, 0.05, 0]}
                            rotation={[0.17, 0.12, 0.28]}>
                            <group
                              name="f_pinky01R"
                              position={[0, 0.04, 0]}
                              rotation={[0.2, -0.04, -0.19]}>
                              <group
                                name="f_pinky02R"
                                position={[0, 0.01, 0]}
                                rotation={[0.04, 0.02, -0.06]}
                              />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group
                    name="spine004"
                    position={[0, 0.07, 0]}
                    rotation={[0.41, 0, 0]}>
                    <group
                      name="spine005"
                      position={[0, 0.03, 0]}
                      rotation={[-0.19, 0, 0]}>
                      <group
                        name="spine006"
                        position={[0, 0.02, 0]}
                        rotation={[-0.19, 0, 0]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group
              name="thighL"
              position={[0.07, 0.02, 0.01]}
              rotation={[2.74, 0, 0]}>
              <group
                name="shinL"
                position={[0, 0.12, 0]}
                rotation={[0.26, 0, 0]}>
                <group
                  name="footL"
                  position={[0, 0.18, 0]}
                  rotation={[-1.47, 0, 0]}>
                  <group
                    name="heel02L"
                    position={[-0.01, -0.03, 0.04]}
                    rotation={[2.94, 0, -Math.PI / 2]}
                  />
                  <group
                    name="toeL"
                    position={[0, 0.1, 0]}
                    rotation={[2.94, 0, Math.PI]}
                  />
                </group>
              </group>
            </group>
            <group
              name="thighR"
              position={[-0.07, 0.02, 0.01]}
              rotation={[2.74, 0, 0]}>
              <group
                name="shinR"
                position={[0, 0.12, 0]}
                rotation={[0.26, 0, 0]}>
                <group
                  name="footR"
                  position={[0, 0.18, 0]}
                  rotation={[-1.47, 0, 0]}>
                  <group
                    name="heel02R"
                    position={[0.01, -0.03, 0.04]}
                    rotation={[2.94, 0, Math.PI / 2]}
                  />
                  <group
                    name="toeR"
                    position={[0, 0.1, 0]}
                    rotation={[2.94, 0, -Math.PI]}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="rig">
          <primitive object={nodes.root} />
          <group name="m_8">
            <skinnedMesh
              name="Mesh017"
              geometry={nodes.Mesh017.geometry}
              material={materials.characters}
              skeleton={nodes.Mesh017.skeleton}
            />
            <skinnedMesh
              name="Mesh017_1"
              geometry={nodes.Mesh017_1.geometry}
              material={materials.scin}
              skeleton={nodes.Mesh017_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/character_final.glb');
